### ISSUE TITLE
Could not scan for classes inside "/wp-graphql-meta-query//src/" which does not appear to be a file nor a folder

### ISSUE THREAD

**Issue by jespervnielsen** [wp-graphql/wp-graphql-meta-query#9]
"Could not scan for classes inside "frontend/wp-content/plugins/wp-graphql-meta-query//src/" which does not appear to be a file nor a folder"

Error message happinging, when installing using composer.

In composerfile, there is a reference to 
```
  "autoload": {
    "psr-4": {
      "WPGraphQL\\MetaQuery\\": "src"
    },
    "classmap": [
      "src/"
    ]
```
But there is no src folder anymore.
Could this just be deleted?

Src folder, was deleted in this commit https://github.com/wp-graphql/wp-graphql-meta-query/commit/4db3cf9411995c7a14399f2d45986ce64af554b3

**Comment by jasonbahl** [comment]
Ah! Ya, it's no longer needed. Need to cleanup the composer file 🤦‍♂

**Comment by jasonbahl** [comment]
@jespervnielsen hey! Can you confirm the latest change addresses this? I believe it does, but would be good if you could confirm as well. If not, let's re-open this
